version: '3.7'

services:
  ts-node-docker:
    container_name: ts-node-dockercontainer
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/src/app/src
      - ./nodemon.json:/home/src/app/nodemon.json
      - ./node_modules:/home/src/app/node_modules
    expose:
      - '3000'
    ports:
      - '3000:3000'
    networks:
      skynet:
        ipv4_address: 192.168.92.25
    command: npm run dev

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ~/dev/docker/mysqldb/data:/var/opt/mysql/data
      - ~/dev/docker/mysqldb/log:/var/opt/mysql/log
      - ~/dev/docker/mysqldb/secrets:/var/opt/mysql/secrets
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      skynet:
        ipv4_address: 192.168.92.21

networks:
  driver: bridge