version: '3.7'

services:
  nodets:
    container_name: ts-node-dockercontainer
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/src/app/src
      - ./nodemon.json:/home/src/app/nodemon.json
      - ./node_modules:/home/src/app/node_modules
    expose:
      - '3000'
    ports:
      - '3000:3000'
    networks:
      - skynet
    depends_on:
      - mysqldb
    command: npm run dev

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    command: ["sh", "/run-always.sh"]
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ~/dev/docker/mysqldb/data:/var/lib/mysql
      - ./dbinit/always.sql:/docker-entrypoint-initdb.d/1_always.sql
      - ./dbinit/run-always.sh:/run-always.sh

    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - skynet

networks:
  skynet:
    driver: bridge